#!/bin/bash

standout="$(tput smso)"
standoutend="$(tput rmso)"

Help()
{
   # Display Help
   echo "Syntax: USE ARGS [-d|-h|-s|-v]"
   echo "options:"
   echo "h:--> Print this Help."
   echo "s:--> Specify GIT ."
}

while getopts d:s:hv flag
	do
	    case "${flag}" in
	        s) source=${OPTARG};;
	        v) echo "V.0.2"
	           exit;;
	        h) Help 
	           exit;;
	    esac
	done

git_recon()
{
	mkdir -p GIT_RECON/TRUFFLEHOG/$1 2>/dev/null
	
	for repo in `curl -s "https://api.github.com/users/$1/repos" \
	| grep -o 'git@[^"]*' \
	| cut -c 16-`
	
		do
			echo -e "${standout}$repo${standoutend}\n"
			
			str=`echo "$repo" \
			| sed 's/\//-/g'`
			
			trufflehog \
			--regex \
			--entropy=False \
			https://github.com/$repo \
			| tee GIT_RECON/TRUFFLEHOG/$1/"$str".txt
			
		done
}

git_recon $source


