#!/bin/bash
###################################################################################################################################################################

if test -t 1; then
    ncolors=$(tput colors)

    if test -n "$ncolors" && test $ncolors -ge 8; then
        bold="$(tput bold)"
        underline="$(tput smul)"
        standout="$(tput smso)"
        standoutend="$(tput rmso)"
        blink="$(tput blink)"
        normal="$(tput sgr0)"
        black="$(tput setaf 0)"
        red="$(tput setaf 1)"
        green="$(tput setaf 2)"
        yellow="$(tput setaf 3)"
        blue="$(tput setaf 4)"
        magenta="$(tput setaf 5)"
        cyan="$(tput setaf 6)"
        white="$(tput setaf 7)"
    fi
fi

###################################################################################################################################################################

declare -a WILD_STRINGS
declare -a Temporary_Domains
declare -a Level_Domains
TOOLS=("CRTSH" "BUFFER" "FINDOMAIN" "SUBFINDER")

file_organize()
{	
	cat ./"$source"/"$source"_"$1".txt 2>/dev/null | sort -u >>  ./"$source"/"$source"_"$1"_final.txt
}

file_merge()
{
	cat ./"$source"/"$source"_"$1"_final.txt ./"$source"/"$source"_"$2"_final.txt ./"$source"/"$source"_"$3"_final.txt ./"$source"/"$source"_"$4"_final.txt  > ./"$source"/"$source".txt
	cat ./"$source"/"$source".txt | sort -u >> ./"$source"/"$source"_final.txt
	rm ./"$source"/"$source"_"$1".txt ./"$source"/"$source"_"$2".txt ./"$source"/"$source"_"$3".txt ./"$source"/"$source"_"$4".txt   ./"$source"/"$source".txt 2>/dev/null
}

###################################################################################################################################################################

Level_Unique()
{
	for i in ${Temporary_Domains[@]} ; 
	do
       		if [ $i == $1 ] ; then
        	    echo "1"
        	fi
       done		
}

###################################################################################################################################################################

Help()
{
   # Display Help
   echo "Syntax: USE ARGS [-d|-h|-s|-v]"
   echo "options:"
   echo "d:--> Specify Sub-Domain Depth.(recommended-3)"
   echo "h:--> Print this Help."
   echo "s:--> Specify Root Domain."
   echo "l:--> Specify Root File."
}

while getopts d:s:l:hv flag
	do
	    case "${flag}" in
	        d) diggy=${OPTARG};;
	        s) source=${OPTARG};;
	        l) list=${OPTARG};;
	        v) echo "V.0.2"
	           exit;;
	        h) Help 
	           exit;;
	    esac
	done
###################################################################################################################################################################	
	
digstring()
{
unset WILD_STRINGS
for (( i = 1; i <= $diggy; i++ ))
do
	wildcard="[^.*$]*\."
	str=""
	for (( j =1; j <= $i; j++ ))
	do
  		str+="${wildcard}"
	done
	WILD_STRINGS[$i-1]="$str$1"
done
}

###################################################################################################################################################################

Query_Gen()
{
	if [[ $1 == "BUFFER" ]] 
	then
		echo "curl -s https://tls.bufferover.run/dns?q=$2 | jq .Results[] 2>/dev/null | cut -d ',' -f 3 | sed 's/*//g' | sed 's/\"//g' | sort -u"
	elif [[ $1 == "CRTSH" ]]
	then
		echo "curl -s https://crt.sh/?Identity=%.$2 | grep \">*.$2\" | sed 's/<[/]*[TB][DR]>/\n/g' | grep -vE \"<|^[\*]*[\.]*$2\" | sort -u | awk 'NF'"
	elif [[ $1 == "FINDOMAIN" ]]
	then
		echo "findomain -q -t $2 2>/dev/null | sort -u"
	elif [[ $1 == "SUBFINDER" ]]
	then
		echo "subfinder -silent -d $2"
	fi
}


###################################################################################################################################################################


extract()
{
for sdm in ${Level_Domains[@]}
do
	for domains in `eval $(Query_Gen $2 $sdm)`
	do
		eval `echo $domains | sed 's/www\.//g' | sed 's/^\.//g' | sed 's/^*\.//g'  >> ./"$source"/"$source"_"$2".txt`
		for items in `echo $domains  | grep -o ${WILD_STRINGS[$1-1]} | sed 's/www\.//g' | sed 's/^\.//g' | sed 's/^*\.//g'`
		do
			tput sc
			echo -ne "\n${standout}${green}$items${normal}${standoutend}"
			sleep 0.03
			tput rc;tput ed
			check=$(Level_Unique $items)
			if [[ $check != 1 ]] ; then
				Temporary_Domains+=($items)
			fi
		done
	done
	
done
}

###################################################################################################################################################################

level()
{
for (( level=1;level<=$diggy;level++))
do
	echo -ne "${normal}${bold}${magenta}${standout}$level-->${standoutend}${normal}"
	extract $level $1
	unset Level_Domains
	Level_Domains=${Temporary_Domains[@]}
	unset Temporary_Domains
done

echo -e "${normal}${bold}${magenta}${standout}end${standoutend}${normal}\n"
}

###################################################################################################################################################################


Query()
{
        mkdir ./"$source" 2>/dev/null
        
        for tool in ${TOOLS[@]}
        do
        	echo -e "${normal}${bold}${cyan}${standout}$tool EXTRACTION${standoutend}${normal}"
        	Level_Domains=($source)
        	level "$tool" 
        	unset Level_Domains
        	unset Temporary_Domains
        	file_organize "$tool"
        done
}


###################################################################################################################################################################

# INCLUDING LIST FLAG (UGLY IF/ELSE)

if [[ -z $source ]] && [[ -z $list ]];
then
	echo "${red}flags not specified${normal}"
elif [[ ! -z $source ]] && [[ ! -z $list ]];
then
	echo "${red}target not clear:--> (use -h)${normal}"
elif  [[ ! -z $source ]] && [[  -z $list ]];
then
	clear
	echo -e "${normal}${bold}${red}${standout}$source${normal}${cyan}\n"	
	digstring $source
	Query
	file_merge "CRTSH" "FINDOMAIN" "BUFFER" "SUBFINDER"
elif [[ -z $source ]] && [[ ! -z $list ]];
then
	while read -r line; do
	if [[ ! -z $line ]]
	then
		clear
		echo -e "${normal}${bold}${red}${standout}$line${standoutend}${normal}${cyan}\n"
		digstring $line
		source=$line
		Query 
		file_merge "CRTSH" "FINDOMAIN" "BUFFER" "SUBFINDER"
		clear
	fi

	done < $list
else
	echo "${red}code flaw${normal}"
fi















